# config file for main (trainer)
# example: dir: /path/to/dir
# please use the exact name of the arg attribute as the name of the variable
io:
  checkpoint_path: checkpoints
  save_frequency: 1
  save_logs: True
  logs: /home/juro4948/ciip/logs #base path for logs 
  mem_snapshots: /home/juro4948/ciip/mem_snapshots/
  log_every_n_steps: 1
  wandb: False
  comet_ml: True
  resume: 

comet: #personal
  api_key: 
  project_name: general
  workspace:


model:
  framework: resnet50 #options are resnet18, resnet50, modified_resnet, transformer
  pretrain:
    load: False
    s1_weights: "MOCO" # Only support for resnet50. S1: MOCO
    s2_weights: "MOCO" # Only support for resnet50. S2: MOCO, DINO
  embed_dim: 1024 #512 #512 #1024 #512 #1000
  s1_layers: [3, 4, 6, 3]
  s2_layers: [3, 4, 6, 3]
  width: 32
  s1_patch_size: 16
  s2_patch_size: 16
  s1_resolution: 224
  s2_resolution: 224
  s1_bands: [1, 2]
  s2_bands: [1, 2, 3, 4, 5, 6, 7, 8, 8A, 9, 10, 11, 12] # if using sentinel-2 s2a tier, band 10 is no longer present
  #TODO we should use mixed prevision
  precision: 'amp' #
  grad_clip_norm: 1 #set to 1 when training with amp
  skip_scheduler: False
  # distill_model:
  # distributed: 
  workers: 6 # workers per GPU


#TODO: loss params
loss:
  local_loss: True
  gather_with_grad: True
  cache_labels: True
  vc_enabled: True
  vc_weight: 0.4
  vc_gamma: 1.0
  vc_covariance_weights: [1.0, 1.0]

datamodule:
  batch_size: 128 # batch size per GPU
  world_size:
  rank: 
  horovod: False
  local_rank:
  # local_loss: True
  # gather_with_grad: True
  distributed:
  device:
  distill:
  # siglip: True
  dist_backend:
  dist_url:
  no_set_device_rank:
  siglip: False #True

dataset:
  dataset_type: ssl4eo
  # train_data is true for training and false for validation
  train_data: True
  dimension: 224
  root: /local/ms-data/SSL4EO/ #TODO: documentation about proper directory to run from
  s2_tier: s2c # TOA data from Sentinel-2 tier 1C; s2a for BOA corrections
  use_transforms: False
  
train:
  # fraction of data to use for validation
  # device: cuda
  use_val: False
  val_frac: 0.0
  epochs: 200
  lr: 0.0005
  wd: 0.02
  # lr: 0.0001
  # wd: 0.2
  warmup: 3000
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-8
  val_frequency: 1
  accum_freq: 40
  save_logs: True
  name: ciip_test
  delete_previous_checkpoint: False
  save_most_recent: False
  debug: False # for logger
  seed: 56
  apply_orthogonal_mapping: False

#other placeholders
remote_sync:
remote_sync_frequency:
remote_sync_protocol:
report_to:
log_path:
log_local:
log_level:
wandb:
tensorboard:
tensorboard_path:
distill_pretrained:
distill_model:
distill:
siglip: False #True
grad_checkpointing: 
use_bn_sync:
ddp_static_graph:
trace:
save_logs:
torchcompile:
copy_codebase: