# config file for main (trainer)
# example: dir = /path/to/dir
# please use the exact name of the arg attribute as the name of the variable

[io]
checkpoint_path = 'ciip/open_clip_train/checkpoints'
save_frequency = 5
save_logs = True
log_every_n_steps = 10
wandb = False

[model]
embed_dim = 512
s1_layers = (3, 4, 6, 3) 
s2_layers = (3, 4, 6, 3) 
width = 32
s1_patch_size = 16
s2_patch_size = 16
s1_resolution = 224
s2_resolution = 224
s1_bands = 3
s2_bands = 12
precision = 'fp16' 
grad_clip_norm = None
device = 'cuda' 
accum_freq = 1
skip_scheduler = False
distill = False

[loss]

[datamodule]
batch_size = 2
world_size = 1
rank = 0
horovod = False

[train]
epochs = 10
lr = 0.0001
wd = 0.2
warmup = 10000
beta1 = 0.9
beta2 = 0.999
eps = 1.0e-8
val_frequency = 1
accum_freq = 5
save_logs = True
name = 'ciip_test'

